name: Build and deploy .NET application to Azure Container Apps

on:
  push:
    branches:
    - deploy
    
env:
  
  # alphanumeric string under 14 characters
  RESOURCE_GROUP_NAME: aca-poc-sample

  # specify your preferred region
  REGION: australiaeast

  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURESPN: ${{ secrets.AZURESPN }}

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-dev-cli-apps:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURESPN }}

      - name: Log in with Azure (Client Credentials)
        run: |
          $info = $Env:AZURESPN | ConvertFrom-Json -AsHashtable;
          Write-Host "::add-mask::$($info.clientSecret)"
          azd login `
            --client-id "$($info.clientId)" `
            --client-secret "$($info.clientSecret)" `
            --tenant-id "$($info.tenantId)"
        shell: pwsh
        env:
          AZURESPN: ${{ secrets.AZURESPN }}

      - name: Azure Dev Provision
        run: azd provision --no-prompt
        env:
          AZURE_ENV_NAME: ${{ env.RESOURCE_GROUP_NAME }}
          AZURE_LOCATION: ${{ env.REGION }} 
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure Dev Deploy
        run: azd deploy --no-prompt
        env:
          AZURE_ENV_NAME: ${{ env.RESOURCE_GROUP_NAME }}
          AZURE_LOCATION: ${{ env.REGION }} 
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

